# Generated by Django 4.1.1 on 2022-09-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('homepage', '0002_resumemodel_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemodel',
            name='uploaderName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='userauth.profile'),
            preserve_default=False,
        ),
    ]
